name: ISCO
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.10.0
  - pip
  # 基础依赖
  - numpy>=1.24.4
  - tqdm>=4.66.1
  - pillow>=9.4.0
  # 开发依赖
  - pandas>=2.2.2
  - scikit-image>=0.24.0
  - matplotlib>=3.9.1
  - jupyter>=1.0.0
  - tensorboard>=2.17.0
  - pip:
    # PyTorch相关
    - torch>=2.5.1
    - torchvision>=0.20.1
    # Hydra相关
    - hydra-core>=1.3.2
    - iopath>=0.1.10
    # 额外依赖
    - opencv-python>=4.7.0
    - eva-decord>=0.6.1
    - Flask>=3.0.3
    - Flask-Cors>=5.0.0
    - av>=13.0.0
    - dataclasses-json>=0.6.7
    - gunicorn>=23.0.0
    - imagesize>=1.4.1
    - pycocotools>=2.0.8
    - strawberry-graphql>=0.243.0
    # 开发工具
    - black==24.2.0
    - usort==1.0.2
    - ufmt==2.0.0b2
    - fvcore>=0.1.5.post20221221
    - tensordict>=0.6.0
    - submitit>=1.5.1
    - pyinstaller>=6.4.0 